import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { CheckCircle2, Edit3, Plus, ShieldCheck, Trash2 } from 'lucide-react'
import { usersApi } from '../api'
import { notify } from '../components/ToastHost'
import Pagination from '../components/Pagination'
import Modal from '../components/Modal'
import PageHeader from '../components/PageHeader'
import type { User, UserRole } from '../types'

const roles: Record<UserRole, string> = { admin: 'Администратор', coordinator: 'Координатор', security_officer: 'Безопасность', analyst: 'Аналитик', viewer: 'Наблюдатель' }
type UserForm = { full_name: string; email: string; role: UserRole; password?: string }

export default function UsersPage() {
  const [role, setRole] = useState<UserRole | ''>('')
  const [page, setPage] = useState({ skip: 0, limit: 10 })
  const [editing, setEditing] = useState<User | null>(null)
  const [creating, setCreating] = useState(false)
  const qc = useQueryClient()
  const query = useQuery({ queryKey: ['users', role, page], queryFn: () => usersApi.list({ role: role || undefined, ...page }) })
  const create = useMutation({ mutationFn: usersApi.create, onSuccess: () => { qc.invalidateQueries({ queryKey: ['users'] }); setCreating(false); notify('Пользователь создан', 'success') } })
  const update = useMutation({ mutationFn: ({ id, data }: { id: number; data: UserForm }) => usersApi.update(id, data), onSuccess: () => { qc.invalidateQueries({ queryKey: ['users'] }); setEditing(null); notify('Пользователь обновлён', 'success') } })
  const toggle = useMutation({ mutationFn: usersApi.toggle, onSuccess: () => { qc.invalidateQueries({ queryKey: ['users'] }); notify('Статус пользователя изменён', 'success') } })
  const remove = useMutation({ mutationFn: usersApi.remove, onSuccess: () => { qc.invalidateQueries({ queryKey: ['users'] }); notify('Пользователь удалён', 'success') } })
  if (query.isLoading) return <div className="page"><div className="loading">Загрузка пользователей...</div></div>
  return <div className="page"><PageHeader eyebrow="Управление  /  Доступ" title="Пользователи" description="Управление ролями и доступом к операционной панели" action={<button className="button button-primary" onClick={() => setCreating(true)}><Plus size={17} /> Добавить пользователя</button>} /><section className="panel filter-panel"><strong>Фильтр по роли</strong><select value={role} onChange={(event) => { setRole(event.target.value as UserRole | ''); setPage((current) => ({ ...current, skip: 0 })) }}><option value="">Все роли</option>{Object.entries(roles).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><span className="filter-count">Найдено: <strong>{query.data?.total ?? 0}</strong></span></section><section className="panel table-panel"><div className="users-summary"><div><strong>{query.data?.total ?? '—'}</strong><span>учётных записей</span></div><div><CheckCircle2 size={17} /><span>Доступ контролируется политиками ролей</span></div></div><div className="table-wrap"><table><thead><tr><th>Сотрудник</th><th>Роль</th><th>Статус</th><th>Дата регистрации</th><th>Действия</th></tr></thead><tbody>{query.data?.items.map((person) => <tr key={person.id}><td><div className="person-cell"><span className="avatar avatar-table">{person.full_name.slice(0, 1).toUpperCase()}</span><span><strong>{person.full_name}</strong><small>{person.email}</small></span></div></td><td><span className="role-cell"><ShieldCheck size={14} /> {roles[person.role]}</span></td><td><button className={person.is_active ? 'active-status status-button' : 'inactive-status status-button'} onClick={() => toggle.mutate(person.id)}><i /> {person.is_active ? 'Активен' : 'Отключён'}</button></td><td className="muted">{new Intl.DateTimeFormat('ru-RU', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(person.created_at))}</td><td><span className="event-actions"><button className="icon-button" title="Редактировать пользователя" onClick={() => setEditing(person)}><Edit3 size={15} /></button><button className="icon-button danger" title="Удалить пользователя" onClick={() => window.confirm('Удалить пользователя?') && remove.mutate(person.id)}><Trash2 size={15} /></button></span></td></tr>)}</tbody></table></div></section><Pagination skip={page.skip} limit={page.limit} total={query.data?.total || 0} onChange={(skip, limit) => setPage({ skip, limit })} />{(creating || editing) && <UserModal user={editing} loading={create.isPending || update.isPending} error={create.isError || update.isError} onClose={() => { setCreating(false); setEditing(null) }} onSubmit={(data) => editing ? update.mutate({ id: editing.id, data }) : create.mutate({ email: data.email, full_name: data.full_name, role: data.role, password: data.password || '' })} />}</div>
}

function UserModal({ user, onClose, onSubmit, loading, error }: { user: User | null; onClose: () => void; onSubmit: (data: UserForm) => void; loading: boolean; error: boolean }) {
  const [form, setForm] = useState<UserForm>(user ? { full_name: user.full_name, email: user.email, role: user.role } : { full_name: '', email: '', role: 'viewer', password: '' })
  const set = (key: keyof UserForm, value: string) => setForm((current) => ({ ...current, [key]: value }))
  return <Modal eyebrow={user ? 'Доступ  /  Редактирование' : 'Доступ  /  Новая учётная запись'} title={user ? 'Изменить пользователя' : 'Добавить пользователя'} onClose={onClose}><form className="modal-form" onSubmit={(event) => { event.preventDefault(); onSubmit(form) }}><label>Имя и фамилия<input required value={form.full_name} onChange={(event) => set('full_name', event.target.value)} /></label><label>Email<input required type="email" value={form.email} onChange={(event) => set('email', event.target.value)} /></label><label>Роль<select value={form.role} onChange={(event) => set('role', event.target.value as UserRole)}>{Object.entries(roles).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label><label>{user ? 'Новый пароль (необязательно)' : 'Пароль'}<input required={!user} minLength={8} type="password" value={form.password || ''} onChange={(event) => set('password', event.target.value)} placeholder="Не менее 8 символов и цифра" /></label>{error && <div className="form-error">Операция не выполнена. Проверьте данные и права.</div>}<div className="modal-actions"><button type="button" className="button button-ghost" onClick={onClose}>Отмена</button><button className="button button-primary" disabled={loading}>{loading ? 'Сохранение...' : user ? 'Сохранить изменения' : 'Создать аккаунт'}</button></div></form></Modal>
}
