import { useEffect } from 'react'
import { Navigate, Route, Routes, useLocation, useNavigate } from 'react-router-dom'
import { authApi } from './api'
import { useAuthStore } from './store'
import AppShell from './components/AppShell'
import DashboardPage from './pages/DashboardPage'
import EventsPage from './pages/EventsPage'
import EventDetailPage from './pages/EventDetailPage'
import IncidentDetailPage from './pages/IncidentDetailPage'
import IncidentsPage from './pages/IncidentsPage'
import LoginPage from './pages/LoginPage'
import MapPage from './pages/MapPage'
import ProfilePage from './pages/ProfilePage'
import UsersPage from './pages/UsersPage'
import RegisterPage from './pages/RegisterPage'
import LoadingScreen from './components/LoadingScreen'
import type { UserRole } from './types'
import { notify } from './components/ToastHost'

function Protected({ children, roles }: { children: JSX.Element; roles?: UserRole[] }) { const { user, bootstrapped } = useAuthStore(); const location = useLocation(); useEffect(() => { if (user && roles && !roles.includes(user.role)) notify('Недостаточно прав для этого раздела', 'error') }, [roles, user]); if (!bootstrapped) return <LoadingScreen />; if (!user) return <Navigate to="/login" state={{ from: `${location.pathname}${location.search}${location.hash}` }} replace />; if (roles && !roles.includes(user.role)) return <Navigate to="/" replace />; return children }
export default function App() { const { user, bootstrapped, setSession, setBootstrapped, clear } = useAuthStore(); const navigate = useNavigate(); const location = useLocation(); useEffect(() => { if (bootstrapped) return; authApi.refresh().then((data) => setSession(data.access_token, data.user)).catch(() => clear()).finally(() => setBootstrapped(true)) }, [bootstrapped, clear, setBootstrapped, setSession]); useEffect(() => { const unauthorized = () => navigate('/login', { replace: true, state: { from: `${location.pathname}${location.search}${location.hash}` } }); window.addEventListener('auth:unauthorized', unauthorized); return () => window.removeEventListener('auth:unauthorized', unauthorized) }, [location.hash, location.pathname, location.search, navigate]); return <Routes><Route path="/login" element={user ? <Navigate to="/" replace /> : <LoginPage />} /><Route path="/register" element={user ? <Navigate to="/" replace /> : <RegisterPage />} /><Route element={<Protected><AppShell /></Protected>}><Route index element={<DashboardPage />} /><Route path="dashboard" element={<DashboardPage />} /><Route path="incidents" element={<IncidentsPage />} /><Route path="incidents/:id" element={<IncidentDetailPage />} /><Route path="map" element={<MapPage />} /><Route path="events" element={<EventsPage />} /><Route path="events/:id" element={<EventDetailPage />} /><Route path="users" element={<Protected roles={['admin']}><UsersPage /></Protected>} /><Route path="profile" element={<ProfilePage />} /></Route><Route path="*" element={<Navigate to="/" replace />} /></Routes> }
